---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
name: silverblue-akmod-kvmfr
description: Latest Fedora Silverblue with Looking Glass KVMFR module

base-image: ghcr.io/ublue-os/silverblue-main
image-version: latest

modules:
  - type: files
    files:
      - source: system
        destination: / 

  - type: rpm-ostree
    repos:
      # %OS_VERSION% still works perfectly here
      - https://copr.fedorainfracloud.org/coprs/hikariknight/looking-glass-kvmfr/repo/fedora-%OS_VERSION%/hikariknight-looking-glass-kvmfr-fedora-%OS_VERSION%.repo

  - type: containerfile
    snippets:
      # Hardcode the tag to main-44 to match your image-version
      - COPY --from=ghcr.io/ublue-os/akmods-extra:main-44 /rpms /tmp/akmods-extra-rpms
      - RUN rpm-ostree install /tmp/akmods-extra-rpms/kmods/*kvmfr*.rpm

  - type: dnf
    remove:
      packages:
        - firefox
        - firefox-langpacks 
        
  - type: signing
