---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
name: silverblue-akmod-kvmfr
description: Latest Fedora Silverblue with Looking Glass KVMFR module

base-image: ghcr.io/ublue-os/silverblue-main
image-version: latest

modules:
  - type: files
    files:
      - source: system
        destination: / 

  - type: rpm-ostree
    repos:
      # Required for the kvmfr-kmod-common dependency
      - https://copr.fedorainfracloud.org/coprs/hikariknight/looking-glass-kvmfr/repo/fedora-%OS_VERSION%/hikariknight-looking-glass-kvmfr-fedora-%OS_VERSION%.repo

  # Replace the standard 'akmods' module with a containerfile module 
  # to fetch the RPM directly from the ublue-os extra stream
  - type: containerfile
    snippets:
      - COPY --from=ghcr.io/ublue-os/akmods:${KERNEL_FLAVOR}-${FEDORA_MAJOR_VERSION} /rpms /tmp/akmods-rpms
      - COPY --from=ghcr.io/ublue-os/akmods-extra:${KERNEL_FLAVOR}-${FEDORA_MAJOR_VERSION} /rpms /tmp/akmods-rpms
      - RUN sed -i 's@enabled=0@enabled=1@g' /etc/yum.repos.d/_copr_ublue-os-akmods.repo && wget https://copr.fedorainfracloud.org/coprs/hikariknight/looking-glass-kvmfr/repo/fedora-"${FEDORA_MAJOR_VERSION}"/hikariknight-looking-glass-kvmfr-fedora-"${FEDORA_MAJOR_VERSION}".repo -O /etc/yum.repos.d/hikariknight-looking-glass-kvmfr-fedora-"${FEDORA_MAJOR_VERSION}".repo && rpm-ostree install /tmp/akmods-rpms/kmods/*kvmfr*.rpm && ostree container commit

  - type: dnf
    remove:
      packages:
        - firefox
        - firefox-langpacks 
        
  - type: signing
